export type Category = {
  id: string;
  name: string;
  group: string;
  description: string;
  actors: string[];
  objects: string[];
  customer: string;
  staff: string;
};

function slug(name: string) {
  return name
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function define(
  group: string,
  name: string,
  description: string,
  actors: string,
  objects: string,
  customer: string,
  staff: string,
): Category {
  return {
    id: slug(name),
    name,
    group,
    description,
    actors: actors.split(", "),
    objects: objects.split(", "),
    customer,
    staff,
  };
}

export const CATEGORIES: Category[] = [
  define(
    "Health",
    "Healthcare / Medical",
    "Applications designed for hospitals, doctors, clinics, patients, medical records, healthcare administration, and related services.",
    "hospitals, doctors, clinics, patients, administrators",
    "medical records, appointments, encounters, referrals, care plans",
    "patients",
    "clinicians and clinic staff",
  ),
  define(
    "Health",
    "Pharmacy",
    "Applications for managing medications, prescriptions, inventory, customers, and pharmacy operations.",
    "pharmacists, technicians, patients, prescribers",
    "prescriptions, medications, inventory lots, refill queues, counseling notes",
    "patients",
    "pharmacy staff",
  ),
  define(
    "Health",
    "Dental",
    "Software designed for dental practices to manage patients, appointments, treatments, records, and billing.",
    "dentists, hygienists, patients, front desk",
    "treatments, charts, appointments, claims, imaging notes",
    "patients",
    "dental practice staff",
  ),
  define(
    "Health",
    "Laboratory Management",
    "Software for managing samples, experiments, equipment, test results, and laboratory workflows.",
    "lab technicians, scientists, requesting clinicians",
    "samples, tests, equipment, results, chain-of-custody logs",
    "requesting clinicians",
    "laboratory staff",
  ),
  define(
    "Health",
    "Biotechnology",
    "Software supporting biological research, scientific data, laboratory processes, and biotechnology operations.",
    "scientists, lab ops, quality teams",
    "assays, batches, protocols, samples, experiment runs",
    "research teams",
    "lab and quality staff",
  ),
  define(
    "Finance",
    "Banking",
    "Applications focused on managing bank accounts, financial transactions, transfers, loans, credit services, and customer banking operations.",
    "customers, tellers, loan officers, operations",
    "accounts, transfers, loans, cards, statements",
    "account holders",
    "bank operations staff",
  ),
  define(
    "Finance",
    "FinTech",
    "Technology-driven financial applications involving payments, investing, budgeting, financial analysis, cryptocurrency, or other modern financial services.",
    "consumers, merchants, analysts",
    "payments, portfolios, budgets, ledgers, KYC records",
    "end users",
    "ops and compliance staff",
  ),
  define(
    "Finance",
    "Insurance",
    "Applications for managing insurance policies, claims, customers, agents, quotes, and coverage information.",
    "policyholders, agents, adjusters, underwriters",
    "policies, quotes, claims, coverage, beneficiaries",
    "policyholders",
    "agents and claims staff",
  ),
  define(
    "Finance",
    "Accounting",
    "Software for managing financial records, expenses, invoices, revenue, and business finances.",
    "accountants, bookkeepers, business owners",
    "invoices, expenses, journals, accounts, reconciliations",
    "clients or the finance team",
    "accountants",
  ),
  define(
    "Finance",
    "Payroll",
    "Applications for calculating and managing employee compensation, pay periods, and payroll records.",
    "employees, payroll admins, managers",
    "pay runs, timesheets, deductions, paystubs, tax records",
    "employees",
    "payroll administrators",
  ),
  define(
    "Education",
    "Education",
    "Applications designed for schools, teachers, students, courses, assignments, grades, and learning management.",
    "teachers, students, parents, administrators",
    "courses, assignments, grades, attendance, classrooms",
    "students",
    "teachers and school staff",
  ),
  define(
    "Education",
    "University / College",
    "Platforms for managing students, courses, campus services, enrollment, academic progress, and university operations.",
    "students, faculty, registrars, advisors",
    "enrollment, courses, transcripts, campus services, terms",
    "students",
    "registrars and faculty",
  ),
  define(
    "Commerce",
    "E-Commerce",
    "Applications for selling products or services online, including product management, customers, orders, and payments.",
    "shoppers, merchants, fulfillment staff",
    "products, carts, orders, payments, shipments",
    "shoppers",
    "store operators",
  ),
  define(
    "Commerce",
    "Retail",
    "Software designed for physical or digital retail businesses, including inventory, sales, customers, employees, and store operations.",
    "associates, managers, shoppers",
    "inventory, POS sales, customers, shifts, store locations",
    "shoppers",
    "store staff",
  ),
  define(
    "Commerce",
    "Marketplace",
    "Platforms where multiple sellers or providers can offer products or services to customers.",
    "buyers, sellers, operators",
    "listings, orders, payouts, reviews, disputes",
    "buyers",
    "marketplace operators",
  ),
  define(
    "Commerce",
    "Subscription Services",
    "Applications based on recurring memberships, billing, account management, and ongoing service access.",
    "subscribers, billing ops, support",
    "plans, invoices, entitlements, dunning, usage",
    "subscribers",
    "billing and support staff",
  ),
  define(
    "Food & Hospitality",
    "Restaurant",
    "Applications for managing restaurant operations, menus, orders, reservations, employees, and customers.",
    "guests, servers, kitchen, managers",
    "menus, tickets, reservations, tables, shifts",
    "diners",
    "front-of-house and kitchen staff",
  ),
  define(
    "Food & Hospitality",
    "Food Delivery",
    "Platforms connecting customers, restaurants, and delivery services to manage food ordering and delivery operations.",
    "customers, restaurants, couriers",
    "menus, orders, deliveries, zones, payouts",
    "hungry customers",
    "dispatch and restaurant staff",
  ),
  define(
    "Food & Hospitality",
    "Hotel / Hospitality",
    "Applications for managing accommodations, guests, reservations, rooms, services, and hospitality operations.",
    "guests, front desk, housekeeping, managers",
    "rooms, reservations, folios, services, housekeeping tasks",
    "guests",
    "hotel staff",
  ),
  define(
    "Food & Hospitality",
    "Recipe / Food Platform",
    "Applications for discovering, creating, organizing, and sharing recipes, meals, and food-related content.",
    "home cooks, creators, editors",
    "recipes, ingredients, collections, meal plans, comments",
    "cooks",
    "editors and creators",
  ),
  define(
    "Travel & Mobility",
    "Travel",
    "Platforms designed to help users discover, plan, organize, and manage trips and travel-related services.",
    "travelers, planners, suppliers",
    "trips, itineraries, bookings, documents, companions",
    "travelers",
    "travel ops",
  ),
  define(
    "Travel & Mobility",
    "Tourism",
    "Applications focused on destinations, attractions, events, visitor information, accommodations, and tourism services.",
    "visitors, operators, destination managers",
    "destinations, attractions, events, visitor guides, stays",
    "visitors",
    "tourism operators",
  ),
  define(
    "Travel & Mobility",
    "Airline / Aviation",
    "Software for managing flights, passengers, bookings, aircraft, schedules, and aviation operations.",
    "passengers, crew, gate agents, ops",
    "flights, bookings, aircraft, crews, schedules",
    "passengers",
    "airline operations staff",
  ),
  define(
    "Travel & Mobility",
    "Car Rental",
    "Applications for managing vehicle availability, reservations, customers, rentals, and fleet operations.",
    "renters, counter staff, fleet managers",
    "vehicles, reservations, contracts, inspections, locations",
    "renters",
    "rental and fleet staff",
  ),
  define(
    "Travel & Mobility",
    "Ride Sharing",
    "Platforms connecting passengers and drivers while managing trips, payments, locations, and transportation services.",
    "passengers, drivers, dispatch",
    "trips, fares, locations, ratings, payouts",
    "passengers",
    "driver ops",
  ),
  define(
    "Travel & Mobility",
    "Public Transportation",
    "Applications involving buses, trains, routes, schedules, tickets, and transportation information.",
    "riders, operators, planners",
    "routes, stops, trips, tickets, service alerts",
    "riders",
    "transit operators",
  ),
  define(
    "Logistics",
    "Logistics",
    "Software focused on coordinating the movement, storage, tracking, and delivery of goods.",
    "shippers, carriers, dispatchers",
    "shipments, stops, tracking events, lanes, exceptions",
    "shippers",
    "logistics coordinators",
  ),
  define(
    "Logistics",
    "Warehouse Management",
    "Applications for managing inventory, storage locations, shipments, employees, and warehouse operations.",
    "pickers, supervisors, inbound clerks",
    "bins, inventory, receipts, picks, shipments",
    "fulfillment customers",
    "warehouse staff",
  ),
  define(
    "Logistics",
    "Shipping",
    "Platforms for managing cargo, containers, shipping routes, deliveries, and transportation operations.",
    "consignees, carriers, port ops",
    "cargo, containers, voyages, bills of lading, deliveries",
    "cargo owners",
    "shipping operations",
  ),
  define(
    "Logistics",
    "Supply Chain Management",
    "Applications that track products and materials as they move between suppliers, manufacturers, warehouses, and customers.",
    "planners, suppliers, warehouse leads",
    "purchase orders, inventory, lead times, nodes, exceptions",
    "downstream customers",
    "supply planners",
  ),
  define(
    "Civic",
    "Smart City",
    "Large-scale platforms representing and managing city services, businesses, events, transportation, public information, and citizen services.",
    "citizens, agencies, operators",
    "services, events, assets, alerts, districts",
    "citizens",
    "city operators",
  ),
  define(
    "Civic",
    "Government",
    "Applications designed for government agencies to manage public services, records, permits, applications, and citizen interactions.",
    "citizens, clerks, case workers",
    "permits, applications, records, cases, appointments",
    "citizens",
    "agency staff",
  ),
  define(
    "Civic",
    "Public Safety",
    "Software supporting emergency services, incident reporting, safety alerts, personnel, and public safety operations.",
    "dispatchers, officers, the public",
    "incidents, alerts, units, reports, shift logs",
    "the public",
    "public safety personnel",
  ),
  define(
    "Civic",
    "Homeowners Association",
    "Platforms for managing residents, properties, maintenance, payments, announcements, and community operations.",
    "residents, board members, managers",
    "units, dues, work orders, votes, announcements",
    "residents",
    "HOA managers",
  ),
  define(
    "Property",
    "Real Estate",
    "Platforms for managing, discovering, buying, selling, or renting residential and commercial properties.",
    "buyers, sellers, agents, renters",
    "listings, showings, offers, clients, comparables",
    "buyers and renters",
    "agents",
  ),
  define(
    "Property",
    "Property Management",
    "Applications for landlords and property managers to manage tenants, buildings, leases, payments, and maintenance.",
    "tenants, landlords, technicians",
    "leases, units, rent, work orders, inspections",
    "tenants",
    "property managers",
  ),
  define(
    "Property",
    "Construction",
    "Software for managing construction projects, workers, schedules, equipment, budgets, and project documentation.",
    "supers, trades, owners, PMs",
    "projects, RFIs, daily logs, equipment, budgets",
    "project owners",
    "site and project staff",
  ),
  define(
    "Industry",
    "Manufacturing",
    "Applications designed to manage production, factories, equipment, inventory, quality control, and supply chains.",
    "operators, planners, QA",
    "work orders, machines, lots, inspections, BOMs",
    "downstream customers",
    "plant staff",
  ),
  define(
    "Industry",
    "Energy / Utilities",
    "Applications for managing electricity, gas, water, renewable energy, consumption, infrastructure, and customers.",
    "customers, field techs, operators",
    "meters, accounts, outages, assets, usage",
    "utility customers",
    "utility operations",
  ),
  define(
    "Industry",
    "Telecommunications",
    "Software for managing communication networks, customers, service plans, devices, and network operations.",
    "subscribers, network ops, support",
    "plans, devices, tickets, outages, accounts",
    "subscribers",
    "telco staff",
  ),
  define(
    "Industry",
    "Franchise Management",
    "Platforms that allow organizations to manage multiple business locations, operations, employees, sales, and corporate data.",
    "franchisees, corporate ops, location managers",
    "locations, playbooks, royalties, audits, sales",
    "franchisees",
    "corporate operators",
  ),
  define(
    "Industry",
    "Enterprise Resource Planning (ERP)",
    "Large-scale business software that combines areas such as finance, inventory, employees, customers, operations, and reporting into one system.",
    "finance, ops, warehouse, HR",
    "items, orders, journals, employees, warehouses",
    "internal business teams",
    "ERP administrators",
  ),
  define(
    "Agriculture & Animals",
    "Agriculture",
    "Software supporting farms, crops, livestock, equipment, harvests, and agricultural operations.",
    "growers, ranchers, agronomists",
    "fields, crops, herds, equipment, harvest lots",
    "farm operators",
    "farm staff",
  ),
  define(
    "Agriculture & Animals",
    "Animal / Pet Services",
    "Applications designed for pet owners, veterinarians, shelters, boarding services, grooming, and animal-related businesses.",
    "pet owners, vets, shelter staff, groomers",
    "pets, visits, boarding stays, adoptions, vaccinations",
    "pet owners",
    "clinic and shelter staff",
  ),
  define(
    "Sports & Wellness",
    "Sports Management",
    "Platforms for managing teams, players, leagues, schedules, statistics, and sporting events.",
    "coaches, players, league admins, fans",
    "teams, rosters, games, stats, venues",
    "players and fans",
    "league staff",
  ),
  define(
    "Sports & Wellness",
    "Fantasy Sports",
    "Applications allowing users to build teams, track player performance, compete in leagues, and manage rankings.",
    "managers, commissioners, fans",
    "leagues, rosters, matchups, scoring, waivers",
    "fantasy managers",
    "commissioners",
  ),
  define(
    "Sports & Wellness",
    "Fitness / Gym",
    "Software for managing workouts, memberships, trainers, classes, fitness progress, and gym operations.",
    "members, trainers, front desk",
    "memberships, classes, workouts, check-ins, trainers",
    "members",
    "gym staff",
  ),
  define(
    "Sports & Wellness",
    "Wellness",
    "Applications focused on personal habits, mindfulness, lifestyle tracking, goals, and general well-being.",
    "individuals, coaches",
    "habits, sessions, goals, journals, streaks",
    "people building routines",
    "coaches",
  ),
  define(
    "Entertainment",
    "Entertainment",
    "Platforms centered around entertainment content, events, media, and user experiences.",
    "audiences, creators, venues",
    "titles, events, tickets, profiles, recommendations",
    "audiences",
    "content operators",
  ),
  define(
    "Entertainment",
    "Movie Theater",
    "Applications for managing movies, showtimes, theaters, tickets, seating, and customer experiences.",
    "moviegoers, box office, projection",
    "films, showtimes, seats, tickets, concessions",
    "moviegoers",
    "theater staff",
  ),
  define(
    "Entertainment",
    "Streaming",
    "Platforms for organizing and delivering video, television, music, or other digital media content.",
    "viewers, catalog editors, creators",
    "titles, seasons, watch history, profiles, catalogs",
    "viewers",
    "catalog editors",
  ),
  define(
    "Entertainment",
    "Music",
    "Applications involving artists, songs, albums, playlists, music discovery, and audio experiences.",
    "listeners, artists, curators",
    "tracks, albums, playlists, follows, plays",
    "listeners",
    "curators",
  ),
  define(
    "Entertainment",
    "Gaming",
    "Platforms related to video games, player accounts, achievements, leaderboards, multiplayer features, and gaming communities.",
    "players, studios, community mods",
    "accounts, matches, achievements, parties, leaderboards",
    "players",
    "community operators",
  ),
  define(
    "Entertainment",
    "Arcade",
    "Applications for managing arcade games, players, tournaments, scores, and entertainment venues.",
    "players, attendants, tournament hosts",
    "cabinets, scores, credits, tournaments, venues",
    "players",
    "arcade staff",
  ),
  define(
    "Entertainment",
    "Events",
    "Software for creating, discovering, organizing, managing, and attending events.",
    "attendees, organizers, vendors",
    "events, sessions, tickets, speakers, venues",
    "attendees",
    "organizers",
  ),
  define(
    "Entertainment",
    "Ticketing",
    "Platforms for selling, managing, validating, and tracking tickets for events, transportation, entertainment, or venues.",
    "buyers, box office, scanners",
    "tickets, holds, scans, refunds, events",
    "ticket buyers",
    "box office staff",
  ),
  define(
    "Entertainment",
    "Theme Park",
    "Applications for managing attractions, visitors, tickets, park information, and entertainment experiences.",
    "guests, ride ops, guest services",
    "attractions, wait times, tickets, reservations, shows",
    "park guests",
    "park operations",
  ),
  define(
    "Entertainment",
    "Museum",
    "Software for managing exhibits, collections, visitors, tickets, memberships, and educational content.",
    "visitors, curators, educators",
    "exhibits, objects, memberships, tours, tickets",
    "visitors",
    "museum staff",
  ),
  define(
    "Entertainment",
    "Art Gallery",
    "Platforms for managing artists, artwork, exhibitions, visitors, and art-related sales or events.",
    "collectors, artists, gallerists",
    "artworks, exhibitions, consignments, inquiries, sales",
    "collectors and visitors",
    "gallery staff",
  ),
  define(
    "Media & Social",
    "Social Media",
    "Applications allowing users to create profiles, share content, interact with others, and build online communities.",
    "members, moderators, creators",
    "posts, follows, comments, feeds, reports",
    "members",
    "moderators",
  ),
  define(
    "Media & Social",
    "Messaging / Communication",
    "Platforms focused on real-time conversations, group communication, notifications, and collaboration.",
    "teammates, friends, admins",
    "threads, messages, channels, receipts, notifications",
    "conversation participants",
    "workspace admins",
  ),
  define(
    "Media & Social",
    "News / Media",
    "Applications for publishing, organizing, discovering, and consuming news and media content.",
    "readers, reporters, editors",
    "articles, sections, editions, bylines, comments",
    "readers",
    "newsroom staff",
  ),
  define(
    "Media & Social",
    "Publishing",
    "Software supporting writers, editors, publishers, and the creation and distribution of written content.",
    "writers, editors, publishers",
    "manuscripts, editions, rights, schedules, reviews",
    "readers",
    "editorial staff",
  ),
  define(
    "Media & Social",
    "Blogging / Content Creation",
    "Platforms that allow users to create, manage, publish, and share digital content.",
    "writers, readers, editors",
    "posts, drafts, tags, comments, media",
    "readers",
    "editors",
  ),
  define(
    "Media & Social",
    "Library",
    "Applications for managing books, digital resources, memberships, borrowing, and library operations.",
    "patrons, librarians",
    "holdings, checkouts, holds, members, fines",
    "patrons",
    "librarians",
  ),
  define(
    "Media & Social",
    "Dating / Social Matching",
    "Applications that connect users based on profiles, interests, preferences, and communication.",
    "members, safety reviewers",
    "profiles, matches, messages, preferences, reports",
    "members",
    "trust and safety staff",
  ),
  define(
    "Work",
    "Human Resources",
    "Software for managing employees, hiring, onboarding, benefits, performance, and workplace information.",
    "employees, HR, managers",
    "employees, time off, reviews, benefits, documents",
    "employees",
    "HR staff",
  ),
  define(
    "Work",
    "Recruitment / Hiring",
    "Platforms for connecting employers and candidates while managing jobs, applications, interviews, and hiring workflows.",
    "candidates, recruiters, hiring managers",
    "requisitions, applications, interviews, scorecards, offers",
    "candidates",
    "recruiters",
  ),
  define(
    "Work",
    "Job Board",
    "Applications where employers publish opportunities and candidates search for and apply to jobs.",
    "job seekers, employers",
    "listings, applications, companies, saved jobs, alerts",
    "job seekers",
    "employers",
  ),
  define(
    "Work",
    "Project Management",
    "Applications for organizing projects, tasks, teams, deadlines, workflows, and progress.",
    "PMs, teammates, stakeholders",
    "projects, tasks, milestones, comments, assignments",
    "project teams",
    "project managers",
  ),
  define(
    "Work",
    "Personal Productivity",
    "Software for managing tasks, goals, notes, schedules, habits, and personal organization.",
    "individuals",
    "tasks, notes, calendars, goals, tags",
    "the person using it",
    "the same user in planning mode",
  ),
  define(
    "Revenue & Ops",
    "CRM / Customer Relationship Management",
    "Software for managing customer information, relationships, sales opportunities, and business interactions.",
    "reps, managers, customers",
    "accounts, contacts, deals, activities, pipelines",
    "customers",
    "sales and success staff",
  ),
  define(
    "Revenue & Ops",
    "Sales Management",
    "Applications designed to track leads, deals, customers, sales performance, and revenue.",
    "AEs, managers, ops",
    "leads, opportunities, quotas, forecasts, activities",
    "prospective customers",
    "sales teams",
  ),
  define(
    "Revenue & Ops",
    "Business Intelligence",
    "Platforms that analyze business data and present insights, reports, dashboards, and performance metrics.",
    "analysts, operators, executives",
    "datasets, metrics, dashboards, reports, alerts",
    "decision makers",
    "analysts",
  ),
  define(
    "Revenue & Ops",
    "Customer Support / Help Desk",
    "Software for managing customer questions, support tickets, agents, and issue resolution.",
    "customers, agents, leads",
    "tickets, macros, SLAs, CSAT, queues",
    "customers",
    "support agents",
  ),
  define(
    "Revenue & Ops",
    "IT Service Management",
    "Applications for managing technology infrastructure, support requests, incidents, assets, and internal IT services.",
    "employees, IT agents, asset owners",
    "incidents, changes, assets, catalogs, SLAs",
    "internal employees",
    "IT staff",
  ),
  define(
    "Revenue & Ops",
    "Document Management",
    "Platforms for uploading, organizing, processing, searching, securing, and managing documents.",
    "knowledge workers, records admins",
    "files, folders, versions, permissions, retention",
    "document owners",
    "records administrators",
  ),
  define(
    "Revenue & Ops",
    "SaaS / Business Software",
    "Subscription-based applications designed to help businesses manage specific workflows or operations.",
    "tenants, admins, end users",
    "workspaces, seats, workflows, billing, audit logs",
    "business users",
    "tenant admins",
  ),
  define(
    "Software & Security",
    "Artificial Intelligence",
    "Applications built around AI models, intelligent assistants, automation, analysis, and AI-powered workflows.",
    "operators, end users, reviewers",
    "prompts, runs, datasets, evaluations, tools",
    "people using the assistant",
    "model operators",
  ),
  define(
    "Software & Security",
    "Knowledge Base / RAG",
    "Systems that organize information and documents so users can search and retrieve knowledge, often using AI, embeddings, and vector search.",
    "readers, authors, admins",
    "documents, chunks, embeddings, answers, citations",
    "people looking something up",
    "knowledge admins",
  ),
  define(
    "Software & Security",
    "Cybersecurity",
    "Applications for monitoring systems, managing security incidents, identifying vulnerabilities, and protecting digital infrastructure.",
    "analysts, responders, asset owners",
    "alerts, incidents, vulns, assets, playbooks",
    "the org being protected",
    "security analysts",
  ),
  define(
    "Software & Security",
    "Identity and Access Management",
    "Software for managing users, authentication, authorization, roles, permissions, and account security.",
    "end users, identity admins, apps",
    "identities, roles, grants, sessions, audit events",
    "workforce or customers",
    "identity administrators",
  ),
  define(
    "Software & Security",
    "IoT / Internet of Things",
    "Applications that connect to and manage physical devices, sensors, equipment, and real-time data.",
    "operators, technicians, devices",
    "devices, telemetry, alerts, firmware, sites",
    "operators watching the fleet",
    "IoT technicians",
  ),
  define(
    "Software & Security",
    "Developer Tools",
    "Applications built for software engineers, such as API platforms, monitoring tools, deployment systems, or development dashboards.",
    "engineers, SREs, platform teams",
    "projects, deploys, logs, APIs, environments",
    "developers",
    "platform engineers",
  ),
  define(
    "Software & Security",
    "Research",
    "Platforms for organizing research materials, data, documents, sources, collaboration, and analysis.",
    "researchers, PIs, collaborators",
    "sources, notes, datasets, citations, collections",
    "researchers",
    "lab or library staff",
  ),
  define(
    "Legal",
    "Legal",
    "Applications for managing legal cases, clients, documents, court schedules, and law firm operations.",
    "attorneys, paralegals, clients",
    "matters, documents, deadlines, time entries, clients",
    "clients",
    "firm staff",
  ),
  define(
    "Legal",
    "Court Management",
    "Software for organizing cases, hearings, documents, attorneys, schedules, and judicial processes.",
    "clerks, judges, attorneys, the public",
    "cases, dockets, hearings, filings, parties",
    "parties to a case",
    "court clerks",
  ),
  define(
    "Mission",
    "Nonprofit",
    "Platforms for managing organizations focused on charitable missions, programs, volunteers, donors, and community impact.",
    "staff, volunteers, beneficiaries, donors",
    "programs, volunteers, grants, outcomes, members",
    "beneficiaries and donors",
    "nonprofit staff",
  ),
  define(
    "Mission",
    "Fundraising / Donations",
    "Applications for creating campaigns, collecting donations, managing donors, and tracking fundraising progress.",
    "donors, campaign managers, finance",
    "campaigns, gifts, pledges, receipts, donor records",
    "donors",
    "fundraising staff",
  ),
  define(
    "Mission",
    "Community Platform",
    "Software that connects people within communities through discussions, events, announcements, and shared resources.",
    "members, moderators, organizers",
    "discussions, events, resources, groups, announcements",
    "community members",
    "moderators",
  ),
  define(
    "Mission",
    "Religious Organization",
    "Applications for managing members, events, donations, volunteers, and organizational communication.",
    "members, clergy, volunteers",
    "members, services, giving, volunteer roles, groups",
    "congregation members",
    "ministry staff",
  ),
  define(
    "Services",
    "Home Services",
    "Platforms connecting customers with service providers such as electricians, plumbers, cleaners, and contractors.",
    "homeowners, providers, dispatch",
    "jobs, quotes, schedules, reviews, payouts",
    "homeowners",
    "provider ops",
  ),
  define(
    "Services",
    "Field Service Management",
    "Software for coordinating technicians, work orders, appointments, equipment, and service operations.",
    "technicians, dispatchers, customers",
    "work orders, routes, parts, SLAs, appointments",
    "service customers",
    "field technicians and dispatch",
  ),
  define(
    "Services",
    "Automotive",
    "Applications related to vehicles, dealerships, maintenance, repairs, inventory, and automotive services.",
    "shoppers, advisors, techs, dealers",
    "vehicles, inventory, service visits, customers, F&I deals",
    "vehicle owners",
    "dealership staff",
  ),
  define(
    "Services",
    "Auto Repair",
    "Software for managing repair shops, service appointments, mechanics, parts, and customer vehicles.",
    "vehicle owners, advisors, mechanics",
    "work orders, inspections, parts, bays, appointments",
    "vehicle owners",
    "shop staff",
  ),
  define(
    "Science",
    "Space / Astronomy",
    "Software involving space data, satellites, astronomy, launches, imagery, and scientific exploration.",
    "researchers, operators, enthusiasts",
    "missions, satellites, observations, imagery, launches",
    "researchers and the public",
    "mission operators",
  ),
  define(
    "Science",
    "Environmental Monitoring",
    "Applications that collect, display, and analyze environmental information such as climate, air, water, or sensor data.",
    "scientists, agencies, the public",
    "stations, samples, readings, alerts, reports",
    "the public and agencies",
    "monitoring staff",
  ),
  define(
    "Science",
    "Weather",
    "Platforms that provide weather conditions, forecasts, alerts, maps, and historical weather information.",
    "the public, forecasters, emergency managers",
    "observations, forecasts, alerts, maps, stations",
    "people checking conditions",
    "forecasters",
  ),
  define(
    "Platforms",
    "Virtual World",
    "Digital environments where users can interact, explore locations, communicate, and participate in activities.",
    "avatars, world builders, moderators",
    "worlds, locations, sessions, inventories, events",
    "players and visitors",
    "world operators",
  ),
  define(
    "Platforms",
    "Digital City",
    "A virtual representation of a city containing businesses, services, locations, events, users, and interactive experiences.",
    "residents, businesses, city ops",
    "places, businesses, events, paths, services",
    "digital residents",
    "city builders",
  ),
];

export const CATEGORY_GROUPS = [
  ...new Set(CATEGORIES.map((category) => category.group)),
];

export const CATEGORY_BY_ID = new Map(
  CATEGORIES.map((category) => [category.id, category]),
);

export function getCategory(id: string | null | undefined) {
  if (!id) return null;
  return CATEGORY_BY_ID.get(id) ?? null;
}

export function shortName(category: Category) {
  return category.name.split(" / ")[0];
}

export function pick(list: string[], index: number) {
  return list[index % list.length];
}
